config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  
  namespace :admin do
    resources :posts do
      resources :comments
    end
  end

  resources :posts do
    resources :comments
  end
end

app/models/admin.rb
class Admin < User
  validates :type, presence: "Admin"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

  def self.search(keyword)
    if keyword.is_a?(String)
      where('body LIKE ?', keyword)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true
  scope :sort_posts_by_asc, -> { order(title: :asc) }
  scope :sort_posts_by_old, -> { order(created_at: :desc) }

  def self.sort_by_comments
    rows = Post.all
    sorted_posts = Hash.new { |k, h|  h[k] = nil}
    for i in rows
      sorted_posts[i] = i.comments.count
    end
    sorted_posts = sorted_posts.sort { |a, b| b[1] <=> a[1] }.to_h
    sorted_posts.keys.each_with_object({}) { |k, h| h[k] = sorted_posts[k] }
    sorted_posts.keys
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: true, presence: true

  def is_admin?
    self.is_a?(Admin)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_action :admin_required!

  def admin_required!
    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_admin?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :find_post, only: [:show, :update, :destroy, :edit]

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def update
    if @post.update(post_params)
      redirect_to [:admin, @post]
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  helper_method :current_user,
                :logged_in?

  def after_sign_in_path_for(resource)
    if resource
      admin_posts_path
    else
      redirect_to posts_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:index, :new, :create]
  before_action :find_comment, only: [:destroy, :edit, :update]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.new()
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post

    if @comment.save!
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @comment.destroy
    redirect_to posts_path
  end

  def update
    if @comment.update(comment_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def edit
    @post = @comment.post
  end

  private

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]
  before_action :sort_posts, only: [:index]

  def index
    @posts
  end

  def show
    @post
  end

  private

  def sort_posts
    if params[:sort_by].present?
      case params[:sort_by]
      when "asc"
        @posts = Post.sort_posts_by_asc
      when "old"
        @posts = Post.sort_posts_by_old
      when "popular"
        @posts = Post.sort_by_comments
      end
    else
      @posts = Post.all
    end
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div>
    <%= link_to "MyBlog", admin_posts_path, class: 'navbar-brand' %>

    <div class="nav-admin user">
      <%= 'Welcome' %> <b><%= current_user.email %></b> Admin
      <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
    </div>
  </div>
</nav>

app/views/admin/posts/_form.html.erb
<%= form_with model: [:admin, @post], locale: true do | form | %>
  <%= render 'shared/errors', resource: @post %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :post_title %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :post_body %>
  </p>

  <p> <%= form.submit %> </p>
<% end %>

app/views/admin/posts/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_posts_path(@post.id) %>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>

<%= render 'shared/errors', resource: @post %>

<p><%= link_to 'Create post', new_admin_post_path %></p>

<table class="table">
    <tr>
      <th>
        Posts
      </th>
      <th>Comments</th>
      <th>Actions</th>
    </tr>
  <% @posts.each do |post| %>
    <tr>
      <td>
        <%= content_tag :span, post.title, class: 'post-title', data: { post_id: post.id } %>
      </td>
      <td><%= post.comments.count %></td>

      <td><%=link_to 'Show', admin_post_path(post) %></td>
      <td>
        <%= link_to 'Edit', edit_admin_post_path(post) %>
      </td>
      <td>
        <%=button_to 'Delete',
        admin_post_path(post),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
      </td>
  <% end %>
    </tr>
</table>

app/views/admin/posts/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_posts_path(@post.id) %>

app/views/admin/posts/show.html.erb
<%= @post.title %>
<%= @post.body %>
<% @post.comments.each do |comment| %>
<%= comment.body%>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @comment], locale: true do | form | %>
  <%= render 'shared/errors', resource: @comment %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :comment_body %>
  </p>

  <p> <%= form.submit %> </p>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', post_comment_path(@post, @comment) %>

app/views/comments/index.html.erb
<h1><% "#{@post.title}" %></h1>

<%= render 'shared/errors', resource: @comment %>

<p><%= link_to 'Create comemnt', new_post_comment_path(@post) %></p>

<table class="table">
    <tr>
      <th>Comments</th>
      <th>Actions</th>
    </tr>
  <% @comments.each do |comment| %>
    <tr>
      <td>
        <%= content_tag :span, comment.body, class: 'comment-body', data: { comment_id: comment.id } %>
      </td>
      <td>
        <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
      </td>
      <td>
        <%=button_to 'Delete',
        post_comment_path(@post, comment),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
      </td>
  <% end %>
    </tr>
</table>

app/views/comments/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', post_path(@post) %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">

    <span class="navbar-text">
      <% if user_signed_in? %>
        <% if current_user.is_admin? %>
          <%= link_to 'MyBlog', admin_posts_path, class: 'navbar-brand' %>
          <p class="nav user">
          Welcome, admin <b><%= current_user.email %></b> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </p>
          <% else %>
          <%= link_to 'MyBlog', posts_path, class: 'navbar-brand' %>
          <p class="nav user">
          Welcome, <b><%= current_user.email %></b> |
          <%= button_to(
            "Log Out",
            destroy_user_session_path,
            method: :delete
          ) %>
          </p>
          <% end %>
      <% else %>
      <%= link_to "Login", new_session_path(resource_name) %>
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
    </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'admin/nav' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render 'shared/errors', resource: @post %>

<table class="table">
  <tr>
    <th> <%=link_to 'Asc', posts_path(sort_by: :asc) %> </th>
    <th> <%=link_to 'Old', posts_path(sort_by: :old) %> </th>
    <th> <%=link_to 'Popular', posts_path(sort_by: :popular) %> </th>
  </tr>
    <tr>
      <th>
        Posts
      </th>
      <th>Comments</th>
    </tr>
  <% @posts.each do |post| %>
    <tr>
      <td>
        <%= content_tag :span, post.title, class: 'post-title', data: { post_id: post.id } %>
      </td>
      <td><%= post.comments.count %></td>

      <td><%=link_to 'Show', post_comments_path(post) %></td>
  <% end %>
    </tr>
</table>

app/views/posts/show.html.erb
<h2>Title: <%= @post.title %></h2>
<h2>Body: <%= @post.body %></h2>
<table class="table">
  <tr>
    <th>Comments:</th>
  </tr>
  <tr>
    <% @post.comments.each do |comment| %>
    <td>
      <%= comment.body%>
    </td>
    <% end %>
  </tr>
</table>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2>
        <%= t('.header', count: resource.errors.count) %>:
      </h2>

      <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>